name: Send Telegram Notification on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  telegram-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install curl
        run: sudo apt-get update && sudo apt-get install curl -y

      - name: Send Telegram message
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
          PULL_REQUEST_URL: ${{ github.event.pull_request.url }}
        run: |
          curl -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage?chat_id=$TELEGRAM_CHAT_ID&text="New pull request created: *$PULL_REQUEST_TITLE* ($PULL_REQUEST_URL)"
            -H "Content-Type: application/json"
